---

- name: Add user jehon
  ansible.builtin.include_role:
    name: jh_user_dev
  vars:
    user: user
    password: pass

- name: Install packages
  ansible.builtin.apt:
    force_apt_get: true
    pkg:
      - jehon
      - jehon-packages
      - jehon-hardware-docker
      - supervisor
      - docker.io
