#
# - https://stackoverflow.com/a/39150040/1954789 (stdin / tty)
#

#volumes:
    # sonar_data:
    # sonar_extensions:

services:
    # apache:
    #     build:
    #         context: apache
    #         dockerfile: Dockerfile
    #     volumes:
    #         - ./apache/webroot:/usr/local/apache2/htdocs:ro
    #     ports:
    #         - 127.0.0.1:9000:80

    jenkins-master:
        # Thanks to https://gist.github.com/pythoninthegrass/abb755a54ba908374e1c8bfd79d0c499
        # Image doc: https://github.com/jenkinsci/docker/blob/master/README.md
        build:
            context: jenkins-master
            dockerfile: Dockerfile
        restart: unless-stopped
        command: --prefix=/jenkins
        volumes:
            # Export configs
            - type: bind
              source: /mnt/docker/jenkins
              target: /mnt/docker/jenkins
        ports:
            - 8080:8080
        expose:
            - 50000
            - 8080
        healthcheck:
            test: curl -fs http://localhost:8080/jenkins/tcpSlaveAgentListener --output /dev/null
            interval: 15s
            timeout: 15s
            retries: 10
            start_period: 30s

    # jenkins_agent_1:
    #     # https://hub.docker.com/r/jenkins/inbound-agent
    #     # https://hub.docker.com/r/jenkins/jnlp-agent-docker
    #     profiles: [ "manual" ]
    #     image: jenkins/jnlp-agent-node
    #     privileged: true
    #     environment:
    #         JENKINS_URL: http://jenkins-master:50000
    #         JENKINS_AGENT_NAME: agent_1
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     command: 
    #     # docker run -i --rm --name jenkins_agent_basic --init jenkins/agent java -jar /usr/share/jenkins/agent.jar
    #     # stdin_open: true # docker run -i
    #     # tty: true        # docker run -t
    #     # user: root
    #     # entrypoint: java
    #     # command: jenkins/jnlp-agent-docker -jar /usr/share/jenkins/agent.jar

    portainer:
        image: portainer/portainer-ce:latest
        # Need to escape all '$' into '$$'
        command: --admin-password='$$2y$$05$$s5BtawHyEHa1fYr9gfeYNOZd8/JAPeAUVfmFlvjGJpNVasmbulNEe'
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - 9000

    # sonar:
    #     build:
    #         context: .
    #         dockerfile: sonar/Dockerfile
    ##     volumes:
    ##         - sonar_data:/opt/sonarqube/data
    ##         - sonar_extensions:/opt/sonarqube/extensions
    #     environment:
    #         SONAR_WEB_CONTEXT: "/sonar"
    #         # SONAR_WEB_PORT: 9080
    #         SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 1
    #     expose:
    #         - 9000
