---

- name: Add user jehon
  ansible.builtin.include_role:
    name: jh_user_dev
  vars:
    user: jehon

- name: Install packages
  ansible.builtin.apt:
    force_apt_get: true
    pkg:
      - jehon
      - jehon-packages
      - jehon-desktop
      - jehon-hardware-hyperv
      - jehon-service-music-refresh
      - docker.io

- name: Set systemd target
  when: jh_is_full_machine
  ansible.builtin.include_role:
    name: jh_systemd_target
  vars:
    target: graphical

- name: Enable photo mount
  when: jh_is_full_machine
  ansible.builtin.systemd:
    name: mnt-cloud-photos.mount
    state: enabled

- name: Fix dns
  ansible.builtin.include_role:
    name: jh_dns

- name: Set docker shared folder
  ansible.builtin.file:
    path: /mnt/docker
    state: directory
    mode: "0755"

- name: Install cryptomedic files
  with_items:
    - cryptomedic.php
    - cryptomedic.sh
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/jehon/restricted/{{ item }}
    owner: root
    group: root
    mode: "0755"

- name: Install dev.sh file
  ansible.builtin.template:
    src: "dev.sh"
    dest: /etc/jehon/restricted/dev.sh
    owner: root
    group: root
    mode: "0755"

- name: Role jh_camera
  ansible.builtin.include_role:
    name: jh_camera
