---

- name: Guess os for jehon-os package
  when: jehon_os_package is undefined or jehon_os_package | length == 0
  block:
    - name: Ensure lsb_module is installed
      ansible.builtin.apt:
        state: present
        pkg:
          - lsb-release

    - name: Recalculate ansible_lsb
      # ansible_lsb (or jehon_deb) depend on lsb-release to be installed => always refresh this value
      ansible.builtin.setup:
        filter:
          # What to recalculate ?
          - ansible_lsb

    - name: Calculate os name from ansible_lsb.id
      when: ansible_lsb.id | length > 0
      ansible.builtin.set_fact:
        jehon_os_package: "jehon-os-{{ ansible_lsb.id | lower }}"

    - name: Fallback jehon_os_package
      ansible.builtin.set_fact:
        jehon_os_package: ""

- name: What is jehon_os_package?
  debug:
    var: jehon_os_package

- name: Detect if it is a full machine or not
  when: jehon_full_machine is undefined
  block:
    - name: Check that /usr/bin/jh-is-full-machine exists
      stat:
        path: /usr/bin/jh-is-full-machine
      register: usr_bin_jh_is_full_machine_stats

    - name: Is full machine
      when: usr_bin_jh_is_full_machine_stats.stat.exists
      block:
        - name: Detect full machine
          ansible.builtin.command:
            cmd: /usr/bin/jh-is-full-machine -q systemd
          register: jehon_full_machine_exec
          failed_when: jehon_full_machine_exec.rc > 1
          changed_when: false

        - name: Register
          ansible.builtin.set_fact:
            jehon_full_machine: "{{ jehon_full_machine_exec.rc == 0 }}"

    - name: Fallback jehon_full_machine
      ansible.builtin.set_fact:
        jehon_full_machine: false

- name: Is full machine?
  debug:
    var: jehon_full_machine
