---

- name: Install wifi config
  ansible.builtin.include_role:
    name: jh_network

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - jehon-service-display
      - jehon-service-music
      - jehon-service-network
      - jehon-service-kiosk

- name: Install kiosk config file
  block:
    - name: Create folder
      ansible.builtin.file:
        path: /opt/jehon/kiosk/etc
        state: directory
        mode: "0755"
    - name: Inject template
      ansible.builtin.template:
        src: kiosk.yml
        dest: /opt/jehon/kiosk/etc/kiosk.yml
        owner: root
        group: root
        mode: "0644"
      notify:
        - host_kiosk.restart-kiosk

- name: Systemd for kiosk
  ansible.builtin.systemd:
    name: jh-kiosk
    enabled: true
    state: started
  when: jh_is_full_machine
