---
all:
  children:
    vm:
      hosts:
        dev:
          # ansible_host is defined by script
          # ansible_host: "{{ jehon.ip.dev }}"
          ansible_connection: local
          become: true
          cloud_type: pcloud-rw
          cloud_cache_size: 20G
          cloud_mount:
            Musiques: rw
            Photos: rw
            Videos: rw
    servers:
      vars:
        cloud_type: home
        cloud_cache_size: 10M
        cloud_mount:
          Musiques: ro
          Photos: ro
          Videos: ro
      hosts:
        kiosk:
          ansible_host: "{{ jehon.ip.kiosk }}"
          ip: "{{ jehon.ip.kiosk }}"
          wifi_ssid: test
          wifi_channel: 1
          wifi_wpa_passphrase: test
          synology:
            username: "{{ jehon.credentials.synology.kiosk.username }}"
            password: "{{ jehon.credentials.synology.kiosk.password }}"
          display_localhost_port: 5454
        piscine:
          ansible_host: "{{ jehon.ip.piscine }}"
          ip: "{{ jehon.ip.piscine }}"
          wifi_ssid: test
          wifi_channel: 6
          wifi_wpa_passphrase: test
          synology:
            username: "{{ jehon.credentials.synology.piscine.username }}"
            password: "{{ jehon.credentials.synology.piscine.password }}"
          display_localhost_port: 8800
  hosts:
    localhost:
      ansible_connection: local
      become: true
    devcontainer:
      ansible_connection: local
      local_repo: /setup/repo
      online_repo: false
