---

- name: Install jehon.deb
  when: "'jehon' not in ansible_facts.packages"
  block:
    - name: Ensure jehon-github repo is configured
      ansible.builtin.copy:
        src: jehon-github.sources
        dest: /etc/apt/sources.list.d/jehon-github.sources
        mode: "0644"
        owner: root
        group: root

    - name: Apt update
      ansible.builtin.apt:
        update_cache: true

    # We need this one to be installed first, because next line will depend on it
    - name: Ensure package jehon is present
      ansible.builtin.apt:
        pkg:
          - jehon

    - name: Apt update (post jehon install)
      ansible.builtin.apt:
        update_cache: true

- name: Install hardware deb
  when: jehon_hardware is defined and jehon_hardware | length > 0
  block:
    - name: Install hardware package
      ansible.builtin.apt:
        pkg:
          - "jehon-hardware-{{ jehon_hardware }}"
      register: jh_common_hardware_installed

    - name: Refresh indexes for hardware
      when: jh_common_hardware_installed.changed
      ansible.builtin.apt:
        update_cache: true

- name: Install OS deb
  block:
    - name: "Install os package: {{ jehon_os_package }}"
      when: jehon_os_package | length > 0
      ansible.builtin.apt:
        pkg:
          - "{{ jehon_os_package }}"
      register: jh_os_installed

    - name: Refresh indexes for OS
      when: jh_os_installed.changed
      ansible.builtin.apt:
        update_cache: true

- name: Configure users
  block:
    - name: Add secrets group
      block:
        - name: Add secrets group
          ansible.builtin.group:
            name: jh_secrets
            state: present
        - name: Create restricted folder
          ansible.builtin.file:
            path: /etc/jehon/restricted/
            state: directory
            owner: root
            group: jh_secrets
            mode: "0755"

    - name: Add jh_pcloud
      ansible.builtin.include_role:
        name: jh_cloud

    - name: Add jh_display
      ansible.builtin.include_role:
        name: jh_display
      when: display_localhost_port is defined

- name: In full machine
  when: jehon_full_machine
  block:
    - name: Set a hostname to {{ inventory_hostname }}
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      when: inventory_hostname is match("[a-zA-Z][a-zA-Z0-9_-]+") and inventory_hostname != "localhost"

    - name: Firewall - allow ssh
      community.general.ufw:
        rule: allow
        name: ssh

    - name: Firewall - enable
      community.general.ufw:
        state: enabled

    - name: Add IP address to hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '.* {{ item }} .* # ansible'
        # TODO: remove hostnames alias without .honlet (!!update regexp!!)
        line: "{{ jehon.ip[item] }} {{ item }}.honlet {{ item }} # ansible"
        state: present
      when: jehon.ip[item] is defined
      with_items: "{{ jehon.ip.keys() }}"
      # On docker, the /etc/hosts is not writable
