---

- name: In full machine
  when: jehon_full_machine
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: List running services
      ansible.builtin.set_fact:
        running_services: >
          "{{ ansible_facts.services
              | dict2items
              | selectattr('value.state', '==', 'running')
              | map(attribute='key')
              | select('search', '.service')
              | list }}"

    # - name: "Debug list of services"
    #   debug:
    #     var: running_services
