---

- name: In full machine
  when: jehon_full_machine
  block:
    # - name: Set systemd target
    #   ansible.builtin.include_role:
    #     name: jh_systemd_target
    #   vars:
    #     target: graphical
    #
    - name: Ensure ubuntu-frame is installed
      community.general.snap:
        name: ubuntu-frame
        state: present
        options:
          - daemon=true
      notify: jh-display.restart

    - name: "Ensure snap {{ display_snap }} is installed"
      community.general.snap:
        name: "{{ display_snap }}"
        state: present
        options:
          - daemon=true
          - devmode=true
          - error-to-console=true
          - "url=http://localhost:{{ display_localhost_port }}"
      notify: jh-display.restart
