---

- name: Ensure DNS
  when: jh_is_full_machine
  block:
    - name: Using resolv.conf.d
      when: /etc/resolvconf/resolv.conf.d/head is file
      notify: jh_dns.resolvconf
      ansible.builtin.lineinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        regexp: '^nameserver '
        line: nameserver {{ dns }}
        state: present

    - name: Using resolv.conf
      when: not ( /etc/resolvconf/resolv.conf.d/head is file )
      notify: jh_dns.resolvconf
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver '
        line: nameserver {{ dns }}
        state: present
