---

- hosts: all
  gather_facts: false

  tasks:
    - debug:
        var: jehon

    - name: Display all variables/facts known for a host {{ inventory_hostname }}
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
