---

- name: Test and debug
  hosts: all
  # gather_facts: no

  tasks:
    - name: Debug jh
      debug:
        var: jh

    - name: Debug ansible
      include_role:
        # name: jh_load_services
        name: jh_is_full_machine

    - name: Debug jh_is_full_machine
      debug:
        var: jh_is_full_machine

    # - name: debug role
    #   include_role:
    #     name: jh_common
    #   # vars:
    #   #   writable: false
