---

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

- name: Upgrade all systems
  hosts: all
  gather_facts: false
  tasks:
    - name: Update packages
  #    when: false
      block:
        - name: Update and upgrade apt packages
          ansible.builtin.apt:
            update_cache: true
            upgrade: full
            autoclean: true
            autoremove: true
            purge: true
          register: apt

  #       - debug: var=apt

        - name: "APT sdtErr"
          when: apt.changed and apt.stderr_lines | length
          ansible.builtin.debug:
            var: apt.stderr_lines

        - name: "APT sdtOut"
          when: apt.changed and apt.stdout_lines | length
          ansible.builtin.debug:
            var: apt.stdout_lines

    - name: Update git's
      # when: false
      ansible.builtin.command: /usr/sbin/jh-git-update
