---

- name: Ensure DNS
  when: jh_is_full_machine
  # Otherwise, folder does not exists (and this has no meaning)
  ansible.builtin.lineinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    regexp: '^nameserver '
    line: nameserver {{ dns }}
    state: present
  notify: jh_dns.resolvconf
