---

# We need this one to be installed first, because next line will depend on it
- name: Setup jehon.deb
  when: "'jehon' not in ansible_facts.packages"
  block:
    - name: Ensure jehon-github repo is configured
      ansible.builtin.copy:
        src: jehon-github.sources
        dest: /etc/apt/sources.list.d/jehon-github.sources
        mode: "0644"
        owner: root
        group: root
      register: jh_jehon_deb_repo

    - name: Apt update
      ansible.builtin.apt:
        update_cache: true

    # We need this one to be installed first, because next line will depend on it
    - name: Ensure package jehon is present
      ansible.builtin.apt:
        pkg:
          - jehon

    - name: Apt update (post jehon install)
      ansible.builtin.apt:
        update_cache: true
      when: jh_jehon_deb_present.changed
