---

- name: Ensure jehon-github repo is configured
  ansible.builtin.copy:
    src: jehon-github.sources
    dest: /etc/apt/sources.list.d/jehon-github.sources
    mode: "0644"
    owner: root
    group: root
  register: jh_jehon_deb_repo

- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  when: jh_jehon_deb_repo.changed

# We need this one to be installed first, because next line will depend on it
- name: Ensure package jehon is present
  ansible.builtin.apt:
    pkg:
      - jehon
  register: jh_jehon_deb_present

- name: Apt update (post jehon install)
  ansible.builtin.apt:
    update_cache: true
  when: jh_jehon_deb_present.changed
